### ISSUE TITLE
building on linux?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#11]
you give instructions for building on windows, but how would i build and install this on linux?

**Comment by wootguy** [comment]
same instructions as windows but without the `-A win32` cmake arg
```
git clone --recurse-submodules https://github.com/wootguy/SevenKewp.git
cd SevenKewp && mkdir build && cd build
cmake ..
cmake --build . --config Release
```

**Comment by Glitch31415** [comment]
oh ok, i thought it was different than that, bc when i do that it errors:

`[  1%] Building CXX object dlls/CMakeFiles/sevenkewp.dir/monsters_base.cpp.o
In file included from /home/glitch/SevenKewp/dlls/./game.h:19,
                 from /home/glitch/SevenKewp/dlls/./util.h:31,
                 from /home/glitch/SevenKewp/dlls/./monster/CBaseMonster.cpp:2,
                 from /home/glitch/SevenKewp/build/dlls/monsters_base.cpp:1:
/home/glitch/SevenKewp/dlls/./CKeyValue.h:14:9: error: ‘uint16_t’ does not name a type
   14 |         uint16_t keyType; // simplified type from keyvalue_types. Key is invalid if this is 0.
      |         ^~~~~~~~
/home/glitch/SevenKewp/dlls/./CKeyValue.h:3:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    2 | #include "extdll.h"
  +++ |+#include <cstdint>
    3 | 
/home/glitch/SevenKewp/dlls/./CKeyValue.h:15:9: error: ‘uint16_t’ does not name a type
   15 |         uint16_t keyOffset;
      |         ^~~~~~~~
/home/glitch/SevenKewp/dlls/./CKeyValue.h:15:9: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
In file included from /home/glitch/SevenKewp/build/dlls/monsters_base.cpp:9:
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘int CGraph::AllocNodes()’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:122:49: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
  122 |         WorldGraph.m_pNodes = (CNode *)calloc ( sizeof ( CNode ), MAX_NODES );
      |                                                 ^~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:122:49: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘void CTestHull::BuildNodeGraph()’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:1648:39: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 1648 |         pTempPool = (CLink *)calloc ( sizeof ( CLink ) , ( WorldGraph.m_cNodes * MAX_NODE_INITIAL_LINKS ) );
      |                                       ^~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:1648:39: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:1942:53: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 1942 |         WorldGraph.m_pLinkPool = (CLink *) calloc ( sizeof ( CLink ), cPoolLinks );
      |                                                     ^~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:1942:53: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘int CGraph::FLoadGraph(char*)’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:2380:48: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2380 |                 m_pNodes = ( CNode * )calloc ( sizeof ( CNode ), m_cNodes );
      |                                                ^~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2380:48: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:2398:51: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2398 |                 m_pLinkPool = ( CLink * )calloc ( sizeof ( CLink ), m_cLinks );
      |                                                   ^~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2398:51: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:2415:45: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2415 |                 m_di = (DIST_INFO *)calloc( sizeof(DIST_INFO), m_cNodes );
      |                                             ^~~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2415:45: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:2432:48: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2432 |                 m_pRouteInfo = (char *)calloc( sizeof(char), m_nRouteInfo );
      |                                                ^~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2432:48: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:2454:48: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2454 |                 m_pHashLinks = (short *)calloc(sizeof(short), m_nHashLinks);
      |                                                ^~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2454:48: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘void CGraph::BuildLinkLookups()’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:2865:40: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2865 |         m_pHashLinks = (short *)calloc(sizeof(short), m_nHashLinks);
      |                                        ^~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2865:40: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘void CGraph::BuildRegionTables()’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:2902:36: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 2902 |         m_di = (DIST_INFO *)calloc(sizeof(DIST_INFO), m_cNodes);
      |                                    ^~~~~~~~~~~~~~~~~
/home/glitch/SevenKewp/dlls/./nodes.cpp:2902:36: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp: In member function ‘void CGraph::ComputeStaticRoutingTables()’:
/home/glitch/SevenKewp/dlls/./nodes.cpp:3310:84: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 3310 |                                  char *Tmp = (char *)calloc(sizeof(char), (m_nRouteInfo + nRoute));
      |                                                             ^~~~~~~~~~~~

/home/glitch/SevenKewp/dlls/./nodes.cpp:3310:84: note: earlier argument should specify number of elements, later size of each element
/home/glitch/SevenKewp/dlls/./nodes.cpp:3323:79: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
 3323 |                               m_pRouteInfo = (char *)calloc(sizeof(char), nRoute);
      |                                                             ^~~~~~~~~~~~

/home/glitch/SevenKewp/dlls/./nodes.cpp:3323:79: note: earlier argument should specify number of elements, later size of each element
gmake[2]: *** [dlls/CMakeFiles/sevenkewp.dir/build.make:76: dlls/CMakeFiles/sevenkewp.dir/monsters_base.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:116: dlls/CMakeFiles/sevenkewp.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
`

**Comment by wootguy** [comment]
which distribution are you building for?

**Comment by Glitch31415** [comment]
debian sid

**Comment by wootguy** [comment]
from a fresh install of debian 12 I had to install these packages to get the code to build:
`apt install build-essential git cmake gcc-multilib g++-multilib libc6-dev-i386`
I had different errors so it might be some other package missing.

**Comment by Glitch31415** [comment]
it must be something else then, i already had all those installed

**Comment by wootguy** [comment]
After switching my sources to sid the build was still working. Not totally sure I did that right.
```
deb http://deb.debian.org/debian/ sid main contrib non-free-firmware
deb-src http://deb.debian.org/debian/ sid main contrib non-free-firmware
```
it might be another package installed that's conflicting, or a different compiler being selected.

**Comment by jyetcv** [comment]
`In file included from /home/user/SevenKewp/dlls/./game.h:19,
                 from /home/user/SevenKewp/dlls/./util.h:31,
                 from /home/user/SevenKewp/dlls/./monster/CBaseMonster.cpp:2,
                 from /home/user/SevenKewp/build/dlls/monsters_base.cpp:1:
/home/user/SevenKewp/dlls/./CKeyValue.h:14:9: error: 'uint16_t' does not name a type
   14 |         uint16_t keyType; // simplified type from keyvalue_types. Key is invalid if this is 0.
      |         ^~~~~~~~
/home/user/SevenKewp/dlls/./CKeyValue.h:3:1: note: 'uint16_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    2 | #include "extdll.h"
  +++ |+#include <cstdint>
    3 | 
/home/user/SevenKewp/dlls/./CKeyValue.h:15:9: error: 'uint16_t' does not name a type
   15 |         uint16_t keyOffset;
      |         ^~~~~~~~
/home/user/SevenKewp/dlls/./CKeyValue.h:15:9: note: 'uint16_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
make[2]: *** [dlls/CMakeFiles/sevenkewp.dir/build.make:76: dlls/CMakeFiles/sevenkewp.dir/monsters_base.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: dlls/CMakeFiles/sevenkewp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`

Similar error.

**Comment by Glitch31415** [comment]
@wootguy what if you just added ```#include <cstdint>``` to every file that uses a ```uint16_t```?

**Comment by wootguy** [comment]
these errors will likely keep coming back until we know what causes this. I can merge a pull request for those includes in the meantime.

**Comment by wootguy** [comment]
As an alternative to building it yourself, github builds a linux binary after each commit now.

Click Actions -> Select the top commit -> download sevenkewp-linux

**Comment by Glitch31415** [comment]
i can't find sevenkewp-linux, i get stuck here https://github.com/wootguy/SevenKewp/actions/runs/10747373032

**Comment by wootguy** [comment]
confused me too at first

![image](https://github.com/user-attachments/assets/fc61374c-5ef7-4131-a168-d9cf050680f1)

**Comment by Glitch31415** [comment]
ok so, i had to rename libstdc++.so.6 and libgcc_s.so.1 to get the server to start (i've had to do that in the past with normal hlds so that might not be a problem) but it immediately segfaults
```
└─$ ./hlds_run -dll dlls/sevenkewp.so -console +map e1m1 +mp_allowmonsters 1 +maxplayers 2
Auto-restarting the server on crash
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
09/10 01:20:46 minidumps folder is set to /tmp/dumps
09/10 01:20:46 Init: Installing breakpad exception handler for appid(70)/version(8684)/tid(4073859)
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:52:19 Aug  3 2020 (8684)
STEAM Auth Server
Server IP address 127.0.1.1:27015
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
crash_20240910012046_2.dmp[4073862]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240910012046_2.dmp
Segmentation fault
crash_20240910012046_2.dmp[4073862]: Finished uploading minidump (out-of-process): success = yes
crash_20240910012046_2.dmp[4073862]: response: Discarded=1
crash_20240910012046_2.dmp[4073862]: file ''/tmp/dumps/crash_20240910012046_2.dmp'', upload yes: ''Discarded=1''
```

**Comment by Glitch31415** [comment]
i reinstalled pretty much everything related to this, and now i think it's working ish but i spawn in dead when i join the server and i can't respawn, no health displays (only armor) and i have a pistol and crowbar with no model that do no damage

**Comment by Glitch31415** [comment]
![Screenshot_2024-09-21_17-00-50](https://github.com/user-attachments/assets/cb7f765f-118c-41d0-8d8a-499ba1a62f2a)

**Comment by Glitch31415** [comment]
> As an alternative to building it yourself, github builds a linux binary after each commit now.
> 
> Click Actions -> Select the top commit -> download sevenkewp-linux

does this negate the need for the "sevenkewp" folder as listed in your building instructions? i can't get that folder because the build still fails

**Comment by Glitch31415** [comment]
alright, so i ended up just cloning the repo, finding all the files that had `uint16_t` in it and just added `#include <cstdint>` manually to the top of each line, and the rest built perfectly, and now the server starts and runs without issue!

**Comment by wootguy** [comment]
hmm missed these comments. The "sevenkewp" files are necessary for sven co-op maps, but the HL campaign might work without it. Best to copy it all to valve_downloads.
