### ISSUE TITLE
multiple dlls at once? (metamod + sevenkewp?)

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#12]
is it possible to load metamod and sevenkewp at once? they both require a different library and it looks like i can only load one or the other, is that the case?

**Comment by Glitch31415** [comment]
i just found rcon is a thing already built into hlds, so this isn't as necessary as i thought it was, but it would still be cool if it was possible to load multiple things at once

**Comment by wootguy** [comment]
yeah, I launch with this:
`./hlds_run -dll addons/metamod/dlls/metamod.so`
then in the metamod config.ini:
`gamedll dlls/sevenkewp.so`

**Comment by Glitch31415** [comment]
oh cool, thanks
