### ISSUE TITLE
how to precache models and sounds manually?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#13]
![Screenshot_2024-09-27_21-13-24](https://github.com/user-attachments/assets/0e75f837-96d4-432a-8d78-576a471a3a0e)
There's also things in the console saying sound files aren't precached. How would I manually add these assets to the precache list?
I've heard there's a 512 item limit for the list, would I just need to choose what things I want to precache sparingly?
(Also, how do I allow instant respawning instead of having to wait for 3 seconds?)

**Comment by Glitch31415** [comment]
Unrelated, but I can't figure out how to enable rtv or map voting, it just goes to the next map in mapcycle.txt without asking the players to vote

**Comment by wootguy** [comment]
I'm guessing you've spawned things with a plugin which is why they aren't precached. To manually add things to the precache list you would need a plugin to call `PRECACHE_MODEL` or `PRECACHE_SOUND` from this mod's code. Or, you can add the entities you want to spawn as inactive monstermaker entities in the BSP. 

Models, sounds, and "generic files" each have a separate 512 item limit.

The RTV plugin on my server is unreleased. You can probably use AMXX with this mod which has tons of plugins for things like that.

**Comment by wootguy** [comment]
`mp_respawndelay 1` to remove the timer.

You might want these cvars to save on precache slots:  
`mp_soundvariety [number]` - sets the max number of sounds a monster can use for an action (pain, attacking, chatting, etc.). This can save 100+ slots depending on which monsters are in the map. `3` is a good starting point.
`mp_mergemodels [0/1]` - toggles the use of merged item models. Should probably always be 1. This can save up to 35 slots.

**Comment by Glitch31415** [comment]
> `mp_respawndelay 1` to remove the timer.
> 
> You might want these cvars to save on precache slots: `mp_soundvariety [number]` - sets the max number of sounds a monster can use for an action (pain, attacking, chatting, etc.). This can save 100+ slots depending on which monsters are in the map. `3` is a good starting point. `mp_mergemodels [0/1]` - toggles the use of merged item models. Should probably always be 1. This can save up to 35 slots.

alright, i'll look into this more in a bit
i'm getting the rtv plugin set up, and i noticed that all the side menu options above 5 don't work (6, 7, 8, 9, and 0 don't do anything). How do I fix this?

**Comment by Glitch31415** [comment]
ok i fixed it by binding the keys to the higher slots like other people did, but should i still limit the maps shown in rtv to 4 so people without this fix are still able to choose the extend map option?

**Comment by Glitch31415** [comment]
as for the model precaching, i might have to write my own plugin for it, that'll be something

**Comment by wootguy** [comment]
not ideal but adding more precache lines here would be a quick way to do what you want:
https://github.com/wootguy/SevenKewp/blob/master/dlls/CWorld.cpp#L191
I don't have an example metamod plugin that uses the mod api yet, and the built-in system is missing a lot of basic stuff.

> should i still limit the maps shown in rtv to 4  

that's what I did. You can ask players to bind the higher slots but realistically most won't do that. It used to be possible to force those binds on players with "slowhacking" but that's blocked now.

**Comment by Glitch31415** [comment]
i'm using some small plugins to precache stuff, i got the sounds all precached fine, but the viewmodels for the weapons refuse to work, they all still show with the model not precached text in the bottom right

this is the list of the file names i'm sending directly to precache_model:
`
models/hlcoop_v2/v_bgrap.mdl
models/hlcoop_v2/v_displacer.mdl
models/hlcoop_v2/v_pipe_wrench.mdl
models/hlcoop_v2/v_rpg.mdl
models/hlcoop_v2/v_shock.mdl
models/hlcoop_v2/v_spore_launcher.mdl

models/v_9mmar.mdl
models/v_9mmhandgun.mdl
models/v_357.mdl
models/v_ak47.mdl
models/v_aug.mdl
models/v_awp.mdl
models/v_bfg.mdl
models/v_c4.mdl
models/v_chub.mdl
models/v_crossbow.mdl
models/v_crowbar.mdl
models/v_deagle.mdl
models/v_desert_eagle.mdl
models/v_egon.mdl
models/v_elite.mdl
models/v_famas.mdl
models/v_fiveseven.mdl
models/v_flashbang.mdl
models/v_g3sg1.mdl
models/v_galil.mdl
models/v_gauss.mdl
models/v_glock18.mdl
models/v_grenade.mdl
models/v_hegrenade.mdl
models/v_hgun.mdl
models/v_hyperblaster.mdl
models/v_knife.mdl
models/v_knife_r.mdl
models/v_m3.mdl
models/v_m4a1.mdl
models/v_m40a1.mdl
models/v_m249.mdl
models/v_mac10.mdl
models/v_mp5.mdl
models/v_p90.mdl
models/v_p228.mdl
models/v_pipe_wrench.mdl
models/v_plasmarifle.mdl
models/v_qrocket.mdl
models/v_rpg.mdl
models/v_satchel.mdl
models/v_satchel_radio.mdl
models/v_saw.mdl
models/v_scout.mdl
models/v_sg550.mdl
models/v_sg552.mdl
models/v_shield_r.mdl
models/v_shotgun.mdl
models/v_smokegrenade.mdl
models/v_squeak.mdl
models/v_tmp.mdl
models/v_tripmine.mdl
models/v_ump45.mdl
models/v_usp.mdl
models/v_xm1014.mdl
`
i know there's a lot of counter strike models that aren't used there, but this is just for testing
are there other model files that are needed to correctly show the viewmodels?

**Comment by Glitch31415** [comment]
i also get a bunch of messages like this in the client when connected to the server

Tried to link edict 949 without model
Tried to link edict 958 without model
Tried to link edict 959 without model
Tried to link edict 960 without model
Tried to link edict 938 without model
Tried to link edict 942 without model
Tried to link edict 944 without model
Tried to link edict 947 without model
Tried to link edict 949 without model
Tried to link edict 958 without model
Tried to link edict 959 without model
Tried to link edict 960 without model

**Comment by wootguy** [comment]
I'm guessing the plugin is calling the wrong version of `PRECACHE_MODEL`. There's the engine function and the mod function by the same name. If you're using a metamod plugin then you'll need to [load the mod api](https://github.com/wootguy/mmlib/blob/master/src/meta_init.cpp#L49). Or you can edit the mod code for now.

**Comment by Glitch31415** [comment]
i'm using amx mod x, so yeah it would be the wrong version then

**Comment by Glitch31415** [comment]
> I'm guessing the plugin is calling the wrong version of `PRECACHE_MODEL`. There's the engine function and the mod function by the same name. If you're using a metamod plugin then you'll need to [load the mod api](https://github.com/wootguy/mmlib/blob/master/src/meta_init.cpp#L49). Or you can edit the mod code for now.

i don't know how to implement that function into my code, i've never coded with amxx before
here's the code for the plugin i'm using, could you add it in for me

```/*
* AMXMODX script
* simple precaching script
* depends on amxmodx/configs/precache.ini
*/

#include <amxmodx>
#include <engine>
#include <amxmisc>


public plugin_init()
{
    register_plugin("mprecache", "1.0", "hjvl")
}

public plugin_precache()
{
	new conffile[200]
	new configdir[200]

	get_configsdir(configdir,199)
	format(conffile,199,"%s/mprecache.ini",configdir)
	if(!file_exists(conffile))
	{
		log_amx("amxmodx/configs/mprecache.ini is missing!")
		return 0
	}

	new lines = file_size(conffile,1)
	new file[1024], len
	for(new i=0;i<=lines;i++)
	{
		read_file(conffile,i,file,1023,len)
		if(equal(file,"")) continue;
		if(!equal(file,";",1)) log_amx("precaching model"); log_amx(file); precache_model(file);
	} 
    return PLUGIN_HANDLED
}```

**Comment by wootguy** [comment]
idk how to get amxx to talk to the mod, but I remembered I do have a public plugin that uses the mod api:
https://github.com/wootguy/AntiBlock/blob/master/src/main.cpp#L295
so you can edit that too to get more things precached.

**Comment by Glitch31415** [comment]
> idk how to get amxx to talk to the mod, but I remembered I do have a public plugin that uses the mod api: https://github.com/wootguy/AntiBlock/blob/master/src/main.cpp#L295 so you can edit that too to get more things precached.

this is in angelscript or metamod or something, i don't even know lol
i'm just gonna hardcode it into the mod (since i want it to be static anyway) and go with that

**Comment by Glitch31415** [comment]
yep, modding the mod worked at least

**Comment by Glitch31415** [comment]
world and player models aren't precached but that's fine

**Comment by Glitch31415** [comment]
soooo many sounds are missing, but there's nothing i can do about that, i'd have to load in thousands of them to get all the sounds for all the entities, i guess i'll just keep adding the ones that get used the most until i fill up the 512

**Comment by Glitch31415** [comment]
@wootguy what is the model for the tongue on the grappler barnacle thing? i've loaded in everything i can think of but the tongue is still invisible

**Comment by wootguy** [comment]
another tip for precaching things is to use `UTIL_PrecacheOther` which precaches everything that an entity requires (`UTIL_PrecacheOther("weapon_grapple")` for example).

> this is in angelscript or metamod  

it has has a metamod and angelscript version in the same repo.

**Comment by Glitch31415** [comment]
i did end up using UTIL_PrecacheOther after i found it by myself lol
