### ISSUE TITLE
how to install angelscript plugins?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#14]
i never used angelscript plugins in sven, and i don't know if it's even possible to use them through sevenkewp, if so then how do i install them?

**Comment by wootguy** [comment]
Angelscript isn't supported, and I'm pretty sure that won't ever change. You might find that a lot of those plugins are ports from amxx.

**Comment by Glitch31415** [comment]
yeah i've been using amxx for as much as i can, but in particular this: https://www.moddb.com/mods/sven-co-op-ai-friendly-co-op-bots has no amxx equivalent, so i decided to ask

**Comment by wootguy** [comment]
that one is a port from metamod.
https://github.com/wootguy/rcbot
I'm not sure but I think all that's needed is to replace the `mmlib/include/sven/` headers with the headers from this mod.

**Comment by Glitch31415** [comment]
*/
[ 16%] Building CXX object CMakeFiles/rcbot.dir/src/bot_menu.cpp.o
/home/glitch/rcbot/src/bot_menu.cpp:47:93: error: pasting ""\\y"" and ""Jump"" does not give a valid preprocessing token
   47 | pointIdx != -1 && (waypoints[waypointIdx].flags & flag)) ? ("\\y" ##name "\\w") : ##name)
      |                                                             ^~~~~

/home/glitch/rcbot/src/bot_menu.cpp:198:74: note: in expansion of macro ‘ICOLOR’
  198 | lobals.m_Menus[BOT_MENU_WAYPOINT_GIVE_FLAGS].AddMenuItem(1, ICOLOR("Jump", W_FL_JUMP),BotMenu_Func_Jump_Waypoint);
      |                                                             ^~~~~~

compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/rcbot.dir/build.make:174: CMakeFiles/rcbot.dir/src/bot_menu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/rcbot.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

/*

**Comment by Glitch31415** [comment]
> that one is a port from metamod. https://github.com/wootguy/rcbot It will crash if you try to use it in this mod though. I'm not sure but I think all that's needed is to replace the `mmlib/include/sven/` headers with the headers from this mod.

[ 16%] Building CXX object CMakeFiles/rcbot.dir/src/bot_menu.cpp.o
/home/glitch/rcbot/src/bot_menu.cpp:47:93: error: pasting ""\\y"" and ""Jump"" does not give a valid preprocessing token
   47 | pointIdx != -1 && (waypoints[waypointIdx].flags & flag)) ? ("\\y" ##name "\\w") : ##name)
      |                                                             ^~~~~

/home/glitch/rcbot/src/bot_menu.cpp:198:74: note: in expansion of macro ‘ICOLOR’
  198 | lobals.m_Menus[BOT_MENU_WAYPOINT_GIVE_FLAGS].AddMenuItem(1, ICOLOR("Jump", W_FL_JUMP),BotMenu_Func_Jump_Waypoint);
      |                                                             ^~~~~~

compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/rcbot.dir/build.make:174: CMakeFiles/rcbot.dir/src/bot_menu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/rcbot.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by Glitch31415** [comment]
```
// colored menu items
#define ICOLOR(name, flag) ((waypointIdx != -1 && (waypoints[waypointIdx].flags & flag)) ? ("\\y" ##name "\\w") : ##name)
```
i don't know what to do with this lol
