### ISSUE TITLE
how would i go about adding npc kills and deaths to killfeed (death notice)?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#15]
is it a player-only thing? i couldn't find any plugins for it on any goldsrc game

**Comment by wootguy** [comment]
add `mp_killfeed 2` to the server.cfg to show npc kills in addition to player kills

**Comment by Glitch31415** [comment]
would bots count as players in this case?

**Comment by wootguy** [comment]
yeah that should work

**Comment by Glitch31415** [comment]
alright, i'm waiting for your rcbot build to work before i add bots anyway, and also the server is down rn because i deleted my patched binary AND the files for it so i have to remake it all lol

**Comment by Glitch31415** [comment]
@wootguy does this show npcs killing other npcs as well? i have yet to test with a server with another person in it

**Comment by wootguy** [comment]
it will now if you set `mp_killfeed 3`

mp_killfeed values:
0 = off
1 = players killing players + npcs killing players
2 = players killing players + npcs killing players  + players killing npcs 
3 = players killing players + npcs killing players  + players killing npcs + monsters killing npcs

**Comment by Glitch31415** [comment]
we talked about this in game, but how would I allow assists to show on players as well? my server is configured so players die about as fast as npcs so it would be fairly useful in my case

**Comment by wootguy** [comment]
I won't walk you through it but updating the `LogPlayerDamage` function to work with all NPCs would be my first step ([relevant commit](https://github.com/wootguy/SevenKewp/commit/9113a548bedbd2c7da3655ecf75682c2f613dacf))
