### ISSUE TITLE
How to put players into separate teams (or use no teams at all)?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#18]
I'm trying to get deathmatch-like scores working on my server, but even though mp_teamplay is set to 0 everyone is still on the same team and all "friendly fire" kills give no points.

**Comment by wootguy** [comment]
you'd need to edit [GiveScorePoints](https://github.com/wootguy/SevenKewp/blob/f3f94703e6a08b6166ad7dfa5b28cb619791c6c9/dlls/monster/CBaseMonster.cpp#L4678). Removing the team coloring/scoreboard probably involves `InitHUD` edits at least.

**Comment by Glitch31415** [comment]
It works, thanks
