### ISSUE TITLE
how to remove/fix ragdolls that are just standing up or crouching?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#19]
this isn't a sevenkewp specific issue (i think), but whenever a player dies, their model can "ragdoll" in their standing or crouching pose, and it's distracting when trying to find what models are actually alive players lol
i tried finding how to remove ragdolls entirely but apparently that wasn't possible with a console command nor a plugin

**Comment by wootguy** [comment]
HL server owners, and a few maps on my server, are distributing sven co-op player models. The animations are totally broken but players still use them. Eventually I'll add support for sven models in this mod, but I'm not sure yet how to organize models that have the same name in both games.

You can disable corpses [here](https://github.com/wootguy/SevenKewp/blob/09adb6b10c71e3654c5e7c9d884bb130d8d89831/dlls/CBasePlayer.cpp#L1479) or force sequence number 18 for all players deaths [here](https://github.com/wootguy/SevenKewp/blob/09adb6b10c71e3654c5e7c9d884bb130d8d89831/dlls/CBasePlayer.cpp#L913) (18 is the only death animation that both HL and sven models share).

**Comment by Glitch31415** [comment]
it isn't even model specific, there's standing corpses around my maps with the default "helmet" player model lol

**Comment by wootguy** [comment]
I've seen this happen rarely with HL models too. I don't know how to reproduce it though. If it's happening every time then it might be related to edits you made or some plugin.

**Comment by Glitch31415** [comment]
i'll try the sequence 18 fix you gave... how do I set PLAYER_DIE to sequence 18? just putting an index int of 18 in the place of PLAYER_DIE didn't work

**Comment by wootguy** [comment]
it's a little complicated. I think you need to call `ResetSequenceInfo` after changing `pev->sequence`. There should be an example somewhere.

Doing that won't help though if every model is bugged. Try editing `CopyToBodyQue` instead.

**Comment by Glitch31415** [comment]
![Screenshot_2024-10-06_01-34-13](https://github.com/user-attachments/assets/beea9647-45b1-4a47-83f0-22c0e262d648)
```
	if (pev->deadflag == DEAD_DYING)
	{
		pev->sequence = 18;
		//Once we finish animating, if we're in multiplayer just make a copy of our body right away.
		if (m_fSequenceFinished && g_pGameRules->IsMultiplayer() && pev->movetype == MOVETYPE_NONE)
		{
			CopyToBodyQue(pev);
			pev->modelindex = 0;
		}

		pev->deadflag = DEAD_DEAD;
	}
```
I just shoehorned it in and it works. Usually, the animation plays, then re-plays, then the ragdoll is created, but i was able to see once where an attack anim was playing and the ragdoll would usually have been cloned with it running, but sequence 18 played once before the ragdoll was created so it was fine.

**Comment by Glitch31415** [comment]
actually it doesn't create the ragdoll after... whatever i guess

**Comment by wootguy** [comment]
Those look a lot like sven co-op player models. The HEV especially. 18 is the "gut shot" for those models too, which is the pose they're in.
