### ISSUE TITLE
how to change weapon spread for things like bullet holes, ricochet sounds, tracers, etc?

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#21]
i already have the actual bullet spread working, but the bullet holes and other things are still using the old spread pattern. Is this client-side, or can I modify something here to fix it? I'm pretty sure it goes though `EV_HLDM_FireBullets` but I already went through all the `EV_FireMP5`, etc functions in `ev_hldm.cpp` and it changed nothing.

**Comment by wootguy** [comment]
That stuff is client-side. The only option besides a custom client would be making a new, identical weapon, which isn't predicted at all. It would feel horrible with lag but the effects would look correct.

**Comment by Glitch31415** [comment]
oh, so that's why some of the weapons from Dawn Half-Life felt so shit, they were custom and I was playing with 350 ping. Alright, just wanted to confirm.
