### ISSUE TITLE
rcbot no longer loads for some reason

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#24]
i think your changes yesterday broke rcbot, i can't find any errors but the dll isn't loading

**Comment by wootguy** [comment]
Replace `mmlib/hlcoop.so` with your latest `server.so` and recompile rcbot.

**Comment by Glitch31415** [comment]
OHH ok thanks

**Comment by wootguy** [comment]
just updated rcbot so that it builds like other native plugins (`git clone` rcbot into `SevenKewp/plugins/` then run `build_game_and_plugins.sh`). This way you don't need to copy libraries around.
