### ISSUE TITLE
Error when trying to compile the and the plugins

### ISSUE THREAD

**Issue by NickMarkick** [wootguy/SevenKewp#26]
![image_2024-10-30_015357852](https://github.com/user-attachments/assets/84bc8d55-5e7f-479c-8fb8-7abfce784efa)
I looked into it and the "coop.obj" file doesn't even exist. 

Here's also a log from visual studio: "Error    LNK1104    cannot open file 'coop.obj'    server    D:\Projects\Funny coop server\sevenkewp-sandbox\build\dlls\LINK    1"

**Comment by wootguy** [comment]
I don't have a "coop.cpp" file either and I can see "sevenkewp-sandbox" in your path, so I think you need to ask glitch:
https://github.com/Glitch31415/sevenkewp-sandbox

**Comment by Glitch31415** [comment]
idk what the issue is, and he said it happens with your repo too

**Comment by wootguy** [comment]
1. create a new folder and open a command prompt inside of it (can do this by typing `cmd` into the explorer address bar).
1. run this command `git clone https://github.com/wootguy/SevenKewp`
1. double click `SevenKewp/scripts/build_game_and_plugins.bat`
2. copy the full output and paste here

**Comment by NickMarkick** [comment]
I fixed the problem by git cloning the repo into the windows temp folder

**Comment by NickMarkick** [comment]
I also figured out I had to do a recursive git clone and now it works in the proper folder too
