### ISSUE TITLE
Spawning issue and NPC issue

### ISSUE THREAD

**Issue by NickMarkick** [wootguy/SevenKewp#27]
When I join my server I am already dead and I cannot respawn, the NPCS also seem to be broken since they do not play their animations.

![image](https://github.com/user-attachments/assets/eeb59092-945b-4dd1-b9c3-44431a0f3213)

**Comment by wootguy** [comment]
@Glitch31415 what did you do to [fix this](https://github.com/wootguy/SevenKewp/issues/11#issuecomment-2365362736)?

**Comment by NickMarkick** [comment]
Currently I have metamod with sevenkewp but this keeps happening even without metamod and it also happens with sevenkewp-sandbox

**Comment by wootguy** [comment]
then check that you have `gamedll dlls/server.dll` in the metamod config (`valve/addons/metamod/config.ini`). Did you get any output from `listplugins`?

**Comment by NickMarkick** [comment]
The last time I checked config.ini it was there and I'm gonna check the listplugins tomorrow

**Comment by Glitch31415** [comment]
> @Glitch31415 what did you do to [fix this](https://github.com/wootguy/SevenKewp/issues/11#issuecomment-2365362736)?
> 
> Check that the mod dll is loaded by trying `listplugins` in the console. If nothing happens then check that you have `-dll dlls/server.dll` as a launch parameter for the dedicated server.

I had that issue for a while and it frustrated me so I probably started almost from scratch and it magically fixed itself or something. Usually I remember my solutions to things but not this one.

**Comment by NickMarkick** [comment]
> @Glitch31415 what did you do to [fix this](https://github.com/wootguy/SevenKewp/issues/11#issuecomment-2365362736)?
> 
> Check that the mod dll is loaded by trying `listplugins` in the console. If nothing happens then check that you have `-dll dlls/server.dll` as a launch parameter for the dedicated server.

![image](https://github.com/user-attachments/assets/d2cf84a9-72fa-4b58-af7b-5db534a9612e)

**Comment by NickMarkick** [comment]
Its the same case with -dll dlls/server.dll instead of metamod

**Comment by jyetcv** [comment]
I think you copy over skill.cfg and server.cfg from SevenKewp_data to the valve directory to fix this.

**Comment by NickMarkick** [comment]
> I think you copy over skill.cfg and server.cfg from SevenKewp_data to the valve directory to fix this.

That worked, thanks!

![image](https://github.com/user-attachments/assets/00227b89-cf38-47be-a680-457fe43e6011)
