### ISSUE TITLE
Explosions sometimes nuke the entire map

### ISSUE THREAD

**Issue by NickMarkick** [wootguy/SevenKewp#33]
I get spawned in random locations on the story maps, is there a way to fix that?

**Comment by Glitch31415** [comment]
#23

**Comment by Glitch31415** [comment]
@NickMarkick @wootguy we installed hiem's mod but now instead of progressing to the next map, we just spawn in a random one

**Comment by wootguy** [comment]
I think you can fix that by adding each map to `mapcycle.txt`. Or, ripent each map to use trigger_changelevel instead of trigger_once for the level changes.

**Comment by Glitch31415** [comment]
i'll try that fix later, but @wootguy rn i was just testing stuff and the explosion that kills everything in the map doesn't play any explosion sound, neither the normal one nor the distant one, so presumably, seemingly randomly, the location of the explosion is set to an invalid number or something so the sound breaks and hit distance detection breaks

idk what would be causing it, i'm going to debug it, do you have any ideas?

**Comment by Glitch31415** [comment]
nope, just found the problem, it happens when the explosion goes off inside a wall or other place outside the map, now to figure out why it's outside the map and how to fix it

**Comment by Glitch31415** [comment]
actually it's kinda related to the thing you linked, specifically this sentence
"Explosions that occur outside of a map will penetrate through walls and can kill players that are otherwise shielded by walls."

**Comment by Glitch31415** [comment]
why does it say it's merged, why isn't the fix in sevenkewp?

**Comment by Glitch31415** [comment]
alright i think i fixed the issue @wootguy
change both these sections of code:
```
	// Pull out of the wall a bit
	if ( pTrace->flFraction != 1.0 )
	{
		pev->origin = pTrace->vecEndPos + (pTrace->vecPlaneNormal * (pev->dmg - 24) * 0.6);
	}
```
to this:
```
	// Pull out of the wall a bit
	if ( pTrace->flFraction != 1.0 )
	{
		pev->origin = pTrace->vecEndPos + (pTrace->vecPlaneNormal * 0.6);
	}
	pev->origin.z = pev->origin.z-1;
```

**Comment by Glitch31415** [comment]
for some reason sound from explosions don't play when it's super close to the player btw

**Comment by Glitch31415** [comment]
nvm not fully fixed yet, give me a moment

**Comment by Glitch31415** [comment]
alright i think i fixed the issue @wootguy
for CGrenade.cpp and CEnvExplosion.cpp, where it says "Pull it out of the wall a bit", remove the part that references the damage and move `pev->origin.z` down 1 before the RadiusDamage call and add one right after

for example, for CGrenade.cpp, change this:
```
	// Pull out of the wall a bit
	if ( pTrace->flFraction != 1.0 )
	{
		pev->origin = pTrace->vecEndPos + (pTrace->vecPlaneNormal * (pev->dmg - 24) * 0.6);
	}
```
to this:
```
	// Pull out of the wall a bit
	if ( pTrace->flFraction != 1.0 )
	{
		pev->origin = pTrace->vecEndPos + (pTrace->vecPlaneNormal * 0.6);
	}
```

and this:
```
	RadiusDamage ( pev, pevOwner, pev->dmg, CLASS_NONE, bitsDamageType );
```
to this:
```
	pev->origin.z = pev->origin.z - 1;
	RadiusDamage ( pev, pevOwner, pev->dmg, CLASS_NONE, bitsDamageType );
	pev->origin.z = pev->origin.z + 1;
```

**Comment by Glitch31415** [comment]
you probably don't want to change it because you're staying true to base hl1 behavior but it was annoying me lol

**Comment by wootguy** [comment]
I know a class of player that lives for glitches like this, but I think it should be fixed too. I might add a cvar for this like with `mp_objectboost` (the insane func_pushable speed from the steam_legacy build).

**Comment by Glitch31415** [comment]
having explosions go through walls is a cool mechanic, but it should only go through the wall that the explosion is closest to, in a controlled fashion, not just bypassing every wall and dealing the full damage from the radius

**Comment by Glitch31415** [comment]
also @wootguy the mapcycle.txt thing didn't work
```
c0a0
c0a0a
c0a0b
c0a0c
c0a0d
c0a0e
c1a0
c1a0a
c1a0b
c1a0c
c1a0d
c1a0e
c1a1
c1a1a
c1a1b
c1a1c
c1a1d
c1a1f
c1a2
c1a2a
c1a2b
c1a2c
c1a2d
c1a3
c1a3a
c1a3b
c1a3c
c1a3d
c1a4
c1a4b
c1a4d
c1a4e
c1a4f
c1a4g
c1a4i
c1a4j
c1a4k
c2a1
c2a1a
c2a1b
c2a1c
c2a2
c2a2a
c2a2b1
c2a2b2
c2a2c
c2a2d
c2a2e
c2a2f
c2a2g
c2a2h
c2a3
c2a3a
c2a3b
c2a3c
c2a3d
c2a3e
c2a4
c2a4a
c2a4b
c2a4c
c2a4d
c2a4e
c2a4f
c2a4g
c2a5
c2a5a
c2a5b
c2a5c
c2a5d
c2a5e
c2a5f
c2a5g
c2a5w
c2a5x
c3a1
c3a1a
c3a1b
c3a2
c3a2a
c3a2b
c3a2c
c3a2d
c3a2e
c3a2f
c4a1
c4a1a
c4a1b
c4a1c
c4a1d
c4a1e
c4a1f
c4a2
c4a2a
c4a2b
c4a3
c5a1
d1_trainstation_02
d1_town_01
e1m1
sandbox
sc_test
crossfireXL
boot_camp
d1_town_03
d1_town_04
stalkyard
hldm_2fort
dead-dust2
lambda_bunker_extended
coolrig
```
still sends me to a random location in a random map

**Comment by wootguy** [comment]
moving that to #34
