### ISSUE TITLE
gauss gun secondary fire does no damage and does not move player

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#36]
all effects and ammo usage are fine, nothing happens though

**Comment by wootguy** [comment]
you need the updated skill.cfg in sevenkewp/

**Comment by Glitch31415** [comment]
didn't help

**Comment by wootguy** [comment]
check the value of `sk_plr_secondarygauss` in console. If it's 0, then check that it's listed in the skill file.

**Comment by Glitch31415** [comment]
it is 0, and it's not in the skill.cfg... what's the default value, i'll just add it in manually

**Comment by wootguy** [comment]
[200](https://github.com/wootguy/SevenKewp_data/blob/master/skill.cfg#L188)
