### ISSUE TITLE
gauss gun secondary fire doesn't trigger the event on the client

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#38]
you can start charging the secondary fire, but when you let go and launch it the sound for the windup still plays on the client and the wind down and wind up animations overlap for a few seconds

**Comment by Glitch31415** [comment]
it works sometimes, but not all the time

**Comment by wootguy** [comment]
I haven't heard this happen yet. I tried firing it about 50 times with different charge amounts and the windup cuts off every time. I'm using the steam HL client.

**Comment by Glitch31415** [comment]
i might record a video of it, the sound gets annoying so i just swap to another weapon and back to make it stop

**Comment by Glitch31415** [comment]
this is so annoying, the moment i loaded up OBS the problem fixed itself

**Comment by Glitch31415** [comment]
vaguely fps dependent maybe

**Comment by Glitch31415** [comment]
there, i got it to break again, it does this all the time when i play normally
https://youtu.be/PrktiPv6CQM
@wootguy

**Comment by Glitch31415** [comment]
i don't know where the sevenkewp client is

**Comment by wootguy** [comment]
I don't know how to reproduce this so you'll need to debug and fix this yourself. Revert to earlier commits and remove mods until the problem is gone.

**Comment by Glitch31415** [comment]
@wootguy 
it's definitely a client issue, it happens all the time UNTIL the player dies while the gauss gun is equipped. Then, it never happens, until the entire game is restarted; you can rejoin the server and the issue is still fixed.
any idea of what might be causing this?

**Comment by wootguy** [comment]
I would check the gauss code, weapon registration code, and hud initialization. The order weapons are registered matters. Events break if out of order.
