### ISSUE TITLE
Rocket launcher is sometimes guided by another player's reticle.

### ISSUE THREAD

**Issue by jyetcv** [wootguy/SevenKewp#42]
Sometimes when you fire the rocket launcher, the rocket will go to a target someone else is pointing at with their laser. It seems to happen even if your laser is disabled.

**Comment by jyetcv** [comment]
I figured it was a feature, but I wasn't certain. I don't mind it so much, but it kind of makes unguided rockets useless with how often they will just fly into a wall since people tend to shoot rockets at the same time in co-op. I also wasn't sure if even though I had the laser on, my rocket would still get captured by someone else's aim. I would have to test it some more. If it's part of the game, I'm fine with it either way. I was just making sure it was intended.  Feel free to close this issue if you want, unless you plan on changing how it functions.

**Comment by Glitch31415** [comment]
where's the code that switches targets, i'm going to remove this from my fork

**Comment by wootguy** [comment]
https://github.com/wootguy/SevenKewp/blob/500f60d1490d519c8e4270c3462f5029e2c8aadf/dlls/weapon/CRpg.cpp#L244

**Comment by Glitch31415** [comment]
nvm, i won't lol

**Comment by wootguy** [comment]
Use `mp_rpg_laser_mode` to control rocket laser guidance.

`mp_rpg_laser_mode 0` = HL behavior. Rockets follow a "random" laser within its FOV.
`mp_rpg_laser_mode 1`  = Realistic. Rockets follow the most centered laser. Its target may suddenly change if another laser is significantly closer and nearly the same direction.
`mp_rpg_laser_mode 2`  = Sven behavior. Rockets follow the laser of the player/npc that fired the rocket.
