### ISSUE TITLE
unrelated to this repo

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#43]
i added the gauss gun code to the shotgun, mp5, 357, and 9mm, and now they all have bullet penetration, but now when i kill monsters without anything in the way (no weapon penetration used), it shows twice in the killfeed. it doesn't happen when killing players

**Comment by Glitch31415** [comment]
@wootguy

**Comment by Glitch31415** [comment]
@wootguy

**Comment by Glitch31415** [comment]
it looks like it does damage twice when the bullet penetration / ricochet isn't being used, how do i stop the normal bullet damage thing from running? i thought i replaced it all @wootguy

**Comment by Glitch31415** [comment]
oh, it's FireBulletsPlayer. it actually fires the bullets, rather than just generating the weapon spread, like it does in the cl_dll version :/

**Comment by Glitch31415** [comment]
still happens even after I remove FireBulletsPlayer. I think it happens when the bullet goes through one limb, kills the monster, but goes through another limb, and even though the monster is already killed, it doesn't register as killed because it's in the same frame and it does another batch of damage and kills the monster again, showing twice on the killfeed and doing damage twice. how would i fix this? @wootguy

**Comment by wootguy** [comment]
idk, maybe check if `bits_MEMORY_KILLED` is set properly. That exists to fix problems like you're having now. I have a bug noted that's similar to yours but haven't looked into it yet.
