### ISSUE TITLE
No cooldown on rtv/unrtv console commands

### ISSUE THREAD

**Issue by amyavi** [wootguy/SevenKewp#45]
I'm not sure where the repo for the rtv plugin is, so I'm filing the issue here.

The "rtv" and "unrtv" console commands (not chat commands) bypass the AntiSpam plugin, and do not have any sort of delay required between them. This allows players to do things like `bind mwheeldown "rtv;unrtv"` and spam chat with it.

**Comment by wootguy** [comment]
Fixed. Those weren't supposed to work in console. Server commands are in a private repo for now.
