### ISSUE TITLE
server fires bullets without accounting for the client's punchangle

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#46]
found this while shooting with the 357 with reduced delay between shots. the camera is still raised from the recoil, but shots still fire straight forward. this means that, by compensating for the recoil and aiming where the crosshair now is, the server thinks you're shooting down
how would we go about fixing this? replicating the client's punchangle to the server? getting the raw angle of the player's camera?

**Comment by wootguy** [comment]
adding `punchangle` to `v_angle` when calculating aim diraction should be enough. Maybe there's a desync between the server and client decaying punchangle back to 0.

**Comment by Glitch31415** [comment]
this is the current code:
```
	UTIL_MakeVectors( m_pPlayer->pev->v_angle + m_pPlayer->pev->punchangle );

	Vector vecAiming = gpGlobals->v_forward;
```
idk what UTIL_MakeVectors does, but i tried combinations of v_angle and punchangle instead of v_forward and it didn't change anything
what would be a combination to test?

**Comment by wootguy** [comment]
idk I would start drawing beams (`te_debug_beam()`) to see where the server thinks the player is aiming. MakeVectors creates directional vectors from angles.

**Comment by Glitch31415** [comment]
when i do this:
```
		if ( fFirstBeam )
		{
			m_pPlayer->pev->effects |= EF_MUZZLEFLASH;
			fFirstBeam = 0;
			te_debug_beam(vecSrc, vecDest, 255, RGBA(255, 0, 0));
	

		}
```
the visible beam goes off in seemingly random directions... why?
https://youtu.be/r9luC81l-gY

**Comment by wootguy** [comment]
`vecDest` is either miscalculated or extending so far that it loops around to the other side of the world (+/-65535 units)

**Comment by Glitch31415** [comment]
```
	Vector vecDir = vecAiming + spread;
	Vector vecDest = vecSrc + (vecDir * 8192);
```

**Comment by wootguy** [comment]
try normalizing vecDir with `.Normalize()`

**Comment by Glitch31415** [comment]
i'll keep the distance the same at first but alr

**Comment by Glitch31415** [comment]
didn't help, now i'll change the * 8192 to * 512 to test

**Comment by Glitch31415** [comment]
ok the 512 fixed the tracer, but i want to keep the range, so i'll set it back to 8192 or something after the test
this is what i actually wanted to show
https://youtu.be/nmX-I-N7lng

**Comment by Glitch31415** [comment]
you can see the client bullet holes don't match with where the server sends the hitscan

**Comment by wootguy** [comment]
so the punchangle is client-side only. You can't just set punchangle in the server code because the client and server values will conflict (most likely. Didn't test.). I'd set a new variable for the client punchangle, make it work exactly like punchangle, then update and use that in the weapon for the aim calculation.

**Comment by Glitch31415** [comment]
so basically just copy the client punchangle code and paste it onto the server, which is what i did for the spread calculation, alr

**Comment by Glitch31415** [comment]
actually, i can't assign a new variable to the player bc i can't modify the engine or smth, i remember i tried doing it before and it didn't work
i think i'll try setting the punchangle thing from the server and see what happens

**Comment by Glitch31415** [comment]
this sets it on the client
```
m_pPlayer->pev->punchangle = m_pPlayer->pev->punchangle + Vector(-10, 0, 0);
```
but it desyncs bc it doesn't drop the punchangle the same way i guess

**Comment by Glitch31415** [comment]
the first two shots are correct, but then the serverside angle pulls up compared to the client one

**Comment by Glitch31415** [comment]
![Uploading Screenshot from 2024-12-09 19-01-45.png…]()

**Comment by Glitch31415** [comment]
![Screenshot from 2024-12-09 19-01-45](https://github.com/user-attachments/assets/fcb2fea1-e237-43ed-a161-00febead8b6d)

**Comment by Glitch31415** [comment]
```
m_pPlayer->pev->punchangle = Vector(-10, 0, 0);
```
this syncs the client and the server and it works well enough
