### ISSUE TITLE
rcbot is now broken after the latest commits

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp#50]
nothing else is broken though

**Comment by Glitch31415** [comment]
@wootguy how do i rebuild rcbot for sevenkewp? i forgot... the build scripts are titled build_sven, so idk if i can use them or not

**Comment by wootguy** [comment]
it builds as a native plugin now:
https://github.com/wootguy/SevenKewp?tab=readme-ov-file#building-native-plugins

**Comment by Glitch31415** [comment]
how do i install it? i built the rcbot.so, but when i replaced the old one with it it still doesn't launch

**Comment by Glitch31415** [comment]
nevermind, i understand now, it's your special plugin implementation now instead of metamod, it works now thanks
